title: Whose poems?
author: Rouge Lin
email: rouge_3877@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  Whose poems? Whose poems? 
  Include whose poems?
baseurl: "./whosepoem" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  rouge3877

# Build settings
theme: jekyll-theme-architect